@echo off
call %EnvRoot%\settings\config.cmd
set DOTNET_ROOT=K:\dist\dotnet\unpacked\dotnet-sdk-v6.0.303
set PATH=%DOTNET_ROOT%;%PATH%
set SlnName=z0
set SlnRoot=%~dp0..\%SlnName%
set SlnFilePath=%SlnRoot%\%SlnName%.sln
set ConfigName=Release
set FrameworkMoniker=net6.0
set VerbosityOption=--verbosity normal
set RepoArchive=%RepoArchives%\%SlnName%.zip
set CommitLog=%RepoArchives%\%SlnName%.commit.log
set Artifacts=%SlnRoot%\artifacts
set SlnBuild=%SlnRoot%\artifacts
set BuildLogs=%Artifacts%\logs
set ShellBuildProps=/p:Configuration=Release /p:Platform=x64 /p:DebugType=Embedded -bl:%BuildLogs%\z0.%ProjectName%.binlog
set ProjectBuildProps=/p:Configuration=Release /p:Platform=x64 /p:DebugType=Embedded -bl:%BuildLogs%\z0.%ProjectName%.binlog
set PackBuildProps=/p:Configuration=Release /p:Platform="Any CPU" /p:DebugType=Embedded -bl:%BuildLogs%\z0.pack.binlog
set SlnBuildProps=/p:Configuration=Release /p:DebugType=Embedded -bl:%BuildLogs%\z0.solution.binlog
set BuildToolOptions=-m:24
set BuildTool=dotnet build %BuildToolOptions%
set ProjectRoot=%SlnRoot%\src\%ProjectName%
set ProjectPath=%ProjectRoot%\z0.%ProjectName%.csproj
set ShellBuildCmd=%BuildTool% %ProjectPath% %ShellBuildProps%
set ProjectBuildCmd=%BuildTool% %ProjectPath% %ProjectBuildProps%
set BuildProject=%ProjectBuildCmd%
set BuildSlnCmd=%BuildTool% %SlnFilePath% %SlnBuildProps%


@REM set CfgFile=%SlnRoot%\%SlnName%.cfg
@REM set BuildPrefix=z0
@REM set DotNetVer=6.0.303
@REM set ArchName=x64
@REM set OsName=win
@REM set Configuration=%ConfigName%
@REM set PlatformName="Any CPU"
@REM set RuntimeMoniker=%OsName%-%ArchName%
@REM set SlnArchive=%DevArchives%\%SlnName%
@REM set SlnBuild=%SlnRoot%\artifacts
@REM set SlnCmd=%SlnRoot%\cmd
@REM set SlnPkg=%SlnBuild%\pkg
@REM set SlnBin=%Artifacts%\bin
@REM set SlnDeps=%SlnRoot%\deps
@REM set SlnObj=%Artifacts%\obj
@REM set SlnLogs=%Artifacts%\logs
@REM set SlnTests=%SlnRoot%\test
@REM set SlnArea=%SlnRoot%\%Area%
@REM set ShellPath=%Artifacts%\bin\%BuildPrefix%.%ProjectName%\%ConfigName%\%FrameworkMoniker%\%RuntimeMoniker%\%ToolName%.exe
@REM set NetSdk=%Artifacts%\deps\dotnet
@REM set Reports=%Artifacts%\reports
@REM set Distributions=%Artifacts%\dist
@REM set NuGetDeps=%SlnDeps%\pkg
@REM set SlnDist=%Distributions%\%SlnName%
@REM set BuildLogs=%Artifacts%\logs
@REM set SlnScripts=%SlnRoot%\scripts
@REM set SlnProps=%SlnRoot%\props
@REM set ProjectRoot=%SlnRoot%\src\%ProjectName%
@REM set ProjectScripts=%ProjectRoot%\scripts
@REM set ProjectPath=%ProjectRoot%\%BuildPrefix%.%ProjectName%.csproj
@REM set ProjectSln=%ProjectRoot%\%BuildPrefix%.%ProjectName%.sln
@REM set ProjectBin=%Artifacts%\bin\%BuildPrefix%.%ProjectName%
@REM set TargetBuildRoot=%ProjectBin%\%ConfigName%\%FrameworkMoniker%
@REM set ShellBin=%TargetBuildRoot%\%RuntimeMoniker%
@REM set ProjectObj=%Artifacts%\obj\%BuildPrefix%.%ProjectName%
@REM set ProjectPdb=%Artifacts%\pdb\%BuildPrefix%.%ProjectName%
@REM set ProjectDist=%Distributions%\%ProjectName%
@REM set PublishedShell=%ProjectDist%\%ShellId%.exe
@REM set DeploySln=%SlnScripts%\sln-deploy.cmd
@REM set SlnPath=%SlnArea%\z0.%Area%.sln
@REM set BuildLogs=%Artifacts%\logs
@REM set LibName=z0.%ProjectName%.dll
@REM set TestLog=%BuildLogs%\z0.%ProjectName%.tests.trx
@REM set RootSlnLogPath=%BuildLogs%\%BuildPrefix%.sln.binlog
@REM set RootSlnLogSpec=-bl:%RootSlnLogPath%
@REM set RootSlnPath=%SlnRoot%\z0.sln
@REM set SlnRootPath=%SlnRoot%\z0.sln
@REM set BuildLog=%BuildLogs%\%BuildPrefix%.%ProjectName%.log
@REM set SlnBuildLog=%BuildLogs%\%BuildPrefix%.%SlnName%.log
@REM set BuildLogPath=%BuildLogs%\%BuildPrefix%.%ProjectName%.binlog
@REM set BuildOptions=-graph:true -m:24 -bl:%BuildLogPath%
@REM set BuildTool=dotnet build
@REM set BuildProps=/p:Configuration=%ConfigName% /p:Platform=%PlatformName%
@REM set BuildProject=%BuildTool% %ProjectPath% %BuildProps% %BuildOptions%
@REM set BuildSln=%BuildTool% %RootSlnPath% %BuildProps% %BuildOptions%
@REM set BuildShells=%BuildTool% %SlnRoot%\shells\z0.shells.sln %BuildProps% -bl:%BuildLogs%\z0.shells.binlog; %BuildOptions%
@REM set BuildDeployment=%BuildTool% %~dp0deploy\z0.deploy.sln %BuildProps% -bl:%BuildLogs%\z0.deploy.binlog; %BuildOptions%
@REM set BuildProjectSln=%BuildTool% %ProjectSln% %BuildProps% %BuildOptions%
@REM set PublishSln=%PublishTool% %ProjecSln%
@REM set BuildSlnRoot=%BuildTool% %SlnRoot%\z0.sln %BuildProps% %RootSlnLogSpec%; %BuildOptions%
@REM set ShellName=%ShellId%.exe
@REM set ShellExePath=%TargetBuildRoot%\%RuntimeMoniker%\%ShellName%
@REM set DllShellBin=%TargetBuildRoot%
@REM set DllShellPath=%DllShellBin%\z0.%ProjectName%.exe
@REM set shell=%ShellExePath%
@REM set dllshell=%DllShellPath%
@REM set CleanBuild=rmdir %Artifacts% /s/q
@REM set CleanObj=rmdir %Artifacts%\obj /s/q
@REM set CleanBin=rmdir %Artifacts%\bin \s\q
@REM set CleanProject=rmdir %ProjectBin% /s/q
@REM set CleanNugetDeps=rmdir %NuGetDeps% /s/q
@REM set AddSlnProject=%SlnScripts%\sln-add.cmd
@REM set ProjectDist=%Distributions%\%ProjectName%
@REM set CleanSlnDist=rmdir %Artifacts%\dist /s/q
@REM set CleanSlnBin=rmdir %Artifacts%\bin /s/q
@REM set CleanSlnObj=rmdir %Artifacts%\obj /s/q
@REM set PublishedSln=%Artifacts%\public\bin
@REM set PublishLib=dotnet publish %ProjectPath% --output %ProjectDist% %ConfigOption% %FrameworkOption%
@REM set PublishShell=dotnet publish %ProjectPath% --output %ProjectDist% %ConfigOption% %FrameworkOption% --publish-single-file
@REM set DeployShell=%~dp0scripts\shell-deploy.cmd
@REM set SlnPubRetract=rmdir %PublishedSln%
@REM set RestoreProject=dotnet restore %ProjectPath% --packages %NuGetDeps% --use-current-runtime %VerbosityOption% --force-evaluate
@REM set ProjectNugetConfig=%ProjectRoot%\nuget.config
@REM set LocalRestore=dotnet restore %ProjectPath% --packages %NuGetDeps% --use-current-runtime %VerbosityOption% --force-evaluate --configfile %ProjectNugetConfig%
@REM set ServeSite=http-server %SlnRoot% --port 48005 --ext txt --mimetypes %MimeTypes% --gzip --brotli -o
@REM set RunToolOptions=--project %ProjectPath% --framework %FrameworkMoniker% %ConfigOption% --runtime %RuntimeMoniker% %VerbosityOption% --self-contained
@REM set RunTool=dotnet run %RunToolOptions%
@REM set GitPush=git push -u origin main -v
@REM set CleanBin=rmdir %ProjectBin% /s/q
@REM set CleanObj=rmdir %ProjectObj% /s/q
@REM set CleanSlnBin=rmdir %SlnBin% /s/q
@REM set CleanSlnObj=rmdir %SlnObj% /s/q
@REM set CleanSlnLogs=rmdir %SlnLogs% /s/q
@REM set ArchiveSln=robocopy %SlnRoot% %DevArchives%\z0 /xd %SlnRoot%\.git /v /mir /fp /log:%DevArchives%\z0.archive.log
@REM set ArchiveRepo=git archive -v -o %RepoArchive% HEAD
@REM set DeployCfg=%SlnRoot%\deploy\deploy.cfg
@REM set PlatformDeployment=%EnvB%\tools\z0\bin
@REM set DeployPath=%DevTools%\%BuildPrefix%\bin
@REM set DeployLog=-bl:%BuildLogs%\%BuildPrefix%.%ProjectName%.deploy.binlog
@REM set DeployProps=-p:PublishReadyToRun=true -p:DebugType=pdbonly -p:PublishDocumentationFiles=true -p:CopyLocalLockFileAssemblies=true -p:CopyDebugSymbolsFromPackages=true -p:CopyDocumentationFilesFromPackages=true
@REM set DeployProps=-p:PublishReadyToRun=true -p:DebugType=pdbonly
@REM set DeployApp=dotnet publish %ProjectPath% --output %DeployPath% %ConfigOption% %VerbosityOption% %FrameworkOption% %DeployProps% %DeployLog%
