//-----------------------------------------------------------------------------
// Copyright   :  (c) Chris Moore, 2020
// License     :  MIT
//-----------------------------------------------------------------------------
namespace Z0.Asm
{
    partial class StanfordAsmCatalog
    {
        [Record(TableId), StructLayout(LayoutKind.Sequential)]
        public struct StokeAsmExportRow
        {
            public const string TableId = "stoke.export";

            public ushort Sequence;

            public string OpCode;

            public string Instruction;

            public bool Mode64;

            public string LegacyMode;

            public string EncodingKind;

            public string Properties;

            public string ImplicitRead;

            public string ImplicitWrite;

            public string ImplicitUndef;

            public string Protected;

            public string Cpuid;

            public string AttMnemonic;

            public string Description;
        }

       /* Example:
        | OpCode                                     | Instruction                                | EncodingKind                               | Properties                                 | ImplicitRead                               | ImplicitWrite                              | ImplicitUndef                              | Useful                                     | Protected                                  | Mode64                                     | LegacyMode                                 | Cpuid                                      | AttMnemonic                                | Preferred                                  | Description
        | 04 ib                                      | ADD AL, imm8                               | I                                          | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addb                                       |                                            | Add imm8 to AL.
        | 05 iw                                      | ADD AX, imm16                              | I                                          | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addw                                       |                                            | Add imm16 to AX.
        | 05 id                                      | ADD EAX, imm32                             | I                                          | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addl                                       |                                            | Add imm32 to EAX.
        | REX.W+ 05 id                               | ADD RAX, imm32                             | I                                          | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addq                                       |                                            | Add imm32 sign-extended to 64-bits to RAX.
        | 80 /0 ib                                   | ADD r/m8, imm8                             | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addb                                       |                                            | Add imm8 to r/m8.
        | REX+ 80 /0 ib                              | ADD r/m8, imm8                             | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addb                                       |                                            | Add sign-extended imm8 to r/m64.
        | 81 /0 iw                                   | ADD r/m16, imm16                           | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addw                                       |                                            | Add imm16 to r/m16.
        | 81 /0 id                                   | ADD r/m32, imm32                           | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addl                                       |                                            | Add imm32 to r/m32.
        | REX.W+ 81 /0 id                            | ADD r/m64, imm32                           | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addq                                       |                                            | Add imm32 sign-extended to 64-bits to r/m64.
        | 83 /0 ib                                   | ADD r/m16, imm8                            | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addw                                       | YES                                        | Add sign-extended imm8 to r/m16.
        | 83 /0 ib                                   | ADD r/m32, imm8                            | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addl                                       | YES                                        | Add sign-extended imm8 to r/m32.
        | REX.W+ 83 /0 ib                            | ADD r/m64, imm8                            | MI                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addq                                       | YES                                        | Add sign-extended imm8 to r/m64.
        | 00 /r                                      | ADD r/m8, r8                               | MR                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addb                                       | YES                                        | Add r8 to r/m8.
        | REX+ 00 /r                                 | ADD r/m8, r8                               | MR                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addb                                       | YES                                        | Add r8 to r/m8.
        | 01 /r                                      | ADD r/m16, r16                             | MR                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addw                                       | YES                                        | Add r16 to r/m16.
        | 01 /r                                      | ADD r/m32, r32                             | MR                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addl                                       | YES                                        | Add r32 to r/m32.
        | REX.W+ 01 /r                               | ADD r/m64, r64                             | MR                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addq                                       | YES                                        | Add r64 to r/m64.
        | 02 /r                                      | ADD r8, r/m8                               | RM                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addb                                       |                                            | Add r/m8 to r8.
        | REX+ 02 /r                                 | ADD r8, r/m8                               | RM                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addb                                       |                                            | Add r/m8 to r8.
        | 03 /r                                      | ADD r16, r/m16                             | RM                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addw                                       |                                            | Add r/m16 to r16.
        | 03 /r                                      | ADD r32, r/m32                             | RM                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | V                                          |                                            | addl                                       |                                            | Add r/m32 to r32.
        | REX.W+ 03 /r                               | ADD r64, r/m64                             | RM                                         | RW, R                                      |                                            | E.OF E.SF E.ZF E.AF E.CF E.PF              |                                            |                                            |                                            | V                                          | NE                                         |                                            | addq                                       |                                            | Add r/m64 to r64.
        */
    }
}