dotnet sln add d:\dev\projects\z0\src\agents\z0.agents.csproj
dotnet sln add d:\dev\projects\z0\src\alloc\z0.alloc.csproj
dotnet sln add d:\dev\projects\z0\src\api.code\z0.api.code.csproj
dotnet sln add d:\dev\projects\z0\src\api.md\z0.api.md.csproj
dotnet sln add d:\dev\projects\z0\src\api.specs\z0.api.specs.csproj
dotnet sln add d:\dev\projects\z0\src\archives\z0.archives.csproj
dotnet sln add d:\dev\projects\z0\src\assets\z0.assets.csproj
dotnet sln add d:\dev\projects\z0\src\asm\z0.asm.csproj
dotnet sln add d:\dev\projects\z0\src\asm.core\z0.asm.core.csproj
dotnet sln add d:\dev\projects\z0\src\asm.prototypes\z0.asm.prototypes.csproj
dotnet sln add d:\dev\projects\z0\src\asm.svc\z0.asm.svc.csproj
dotnet sln add d:\dev\projects\z0\src\sys\z0.sys.csproj
dotnet sln add d:\dev\projects\z0\src\text\z0.text.csproj
dotnet sln add d:\dev\projects\z0\src\bit\z0.bit.csproj
dotnet sln add d:\dev\projects\z0\src\types\z0.types.csproj
dotnet sln add d:\dev\projects\z0\src\bit.render\z0.bit.render.csproj
dotnet sln add d:\dev\projects\z0\src\bitmasks\z0.bitmasks.csproj
dotnet sln add d:\dev\projects\z0\src\bitvectors\z0.bitvectors.csproj
dotnet sln add d:\dev\projects\z0\src\blocks\z0.blocks.csproj
dotnet sln add d:\dev\projects\z0\src\bits\z0.bits.csproj
dotnet sln add d:\dev\projects\z0\src\builds\z0.builds.csproj
dotnet sln add d:\dev\projects\z0\src\calcs\z0.calcs.csproj
dotnet sln add d:\dev\projects\z0\src\cg.common\z0.cg.common.csproj
dotnet sln add d:\dev\projects\z0\src\cg.intel\z0.cg.intel.csproj
dotnet sln add d:\dev\projects\z0\src\cg.libs\z0.cg.libs.csproj
dotnet sln add d:\dev\projects\z0\src\cg.llvm\z0.cg.llvm.csproj
dotnet sln add d:\dev\projects\z0\src\cg.shell\z0.cg.shell.csproj
dotnet sln add d:\dev\projects\z0\src\cg.test\z0.cg.test.csproj
dotnet sln add d:\dev\projects\z0\src\circuits\z0.circuits.csproj
dotnet sln add d:\dev\projects\z0\src\clr.query\z0.clr.query.csproj
dotnet sln add d:\dev\projects\z0\src\clr.cil\z0.clr.cil.csproj
dotnet sln add d:\dev\projects\z0\src\clr.checks\z0.clr.checks.csproj
dotnet sln add d:\dev\projects\z0\src\clr.ecma\z0.clr.ecma.csproj
dotnet sln add d:\dev\projects\z0\src\capture\z0.capture.csproj
dotnet sln add d:\dev\projects\z0\src\containers\z0.containers.csproj
dotnet sln add d:\dev\projects\z0\src\cells\z0.cells.csproj
dotnet sln add d:\dev\projects\z0\src\cpu\z0.cpu.csproj
dotnet sln add d:\dev\projects\z0\src\cmd\z0.cmd.csproj
dotnet sln add d:\dev\projects\z0\src\cmd.checks\z0.cmd.checks.csproj
dotnet sln add d:\dev\projects\z0\src\cmd.specs\z0.cmd.specs.csproj
dotnet sln add d:\dev\projects\z0\src\cmd.models\z0.cmd.models.csproj
dotnet sln add d:\dev\projects\z0\src\coff\z0.coff.csproj
dotnet sln add d:\dev\projects\z0\src\db\z0.db.csproj
dotnet sln add d:\dev\projects\z0\src\db.sqlite\z0.db.sqlite.csproj
dotnet sln add d:\dev\projects\z0\src\dispatcher\z0.dispatcher.csproj
dotnet sln add d:\dev\projects\z0\src\digital\z0.digital.csproj
dotnet sln add d:\dev\projects\z0\src\diagnostics\z0.diagnostics.csproj
dotnet sln add d:\dev\projects\z0\src\dynamic\z0.dynamic.csproj
dotnet sln add d:\dev\projects\z0\src\events\z0.events.csproj
dotnet sln add d:\dev\projects\z0\src\emath\z0.emath.csproj
dotnet sln add d:\dev\projects\z0\src\fsm\z0.fsm.csproj
dotnet sln add d:\dev\projects\z0\src\files\z0.files.csproj
dotnet sln add d:\dev\projects\z0\src\graphs\z0.graphs.csproj
dotnet sln add d:\dev\projects\z0\src\grids\z0.grids.csproj
dotnet sln add d:\dev\projects\z0\src\heaps\z0.heaps.csproj
dotnet sln add d:\dev\projects\z0\src\hex\z0.hex.csproj
dotnet sln add d:\dev\projects\z0\src\hub\z0.hub.csproj
dotnet sln add d:\dev\projects\z0\src\intel.svc\z0.intel.svc.csproj
dotnet sln add d:\dev\projects\z0\src\lang\z0.lang.csproj
dotnet sln add d:\dev\projects\z0\src\lang.emit\z0.lang.emit.csproj
dotnet sln add d:\dev\projects\z0\src\literals\z0.literals.csproj
dotnet sln add d:\dev\projects\z0\src\lib\z0.lib.csproj
dotnet sln add d:\dev\projects\z0\src\linq\z0.linq.csproj
dotnet sln add d:\dev\projects\z0\src\llvm.svc\z0.llvm.svc.csproj
dotnet sln add d:\dev\projects\z0\src\math\z0.math.csproj
dotnet sln add d:\dev\projects\z0\src\memory\z0.memory.csproj
dotnet sln add d:\dev\projects\z0\src\memory.svc\z0.memory.svc.csproj
dotnet sln add d:\dev\projects\z0\src\machines\z0.machines.csproj
dotnet sln add d:\dev\projects\z0\src\native\z0.native.csproj
dotnet sln add d:\dev\projects\z0\src\numbers\z0.numbers.csproj
dotnet sln add d:\dev\projects\z0\src\rules\z0.rules.csproj
dotnet sln add d:\dev\projects\z0\src\render\z0.render.csproj
dotnet sln add d:\dev\projects\z0\src\polyrand\z0.polyrand.csproj
dotnet sln add d:\dev\projects\z0\src\process\z0.process.csproj
dotnet sln add d:\dev\projects\z0\src\shell\z0.shell.csproj
dotnet sln add d:\dev\projects\z0\src\sos.cmd\z0.sos.cmd.csproj
dotnet sln add d:\dev\projects\z0\src\symbolics\z0.symbolics.csproj
dotnet sln add d:\dev\projects\z0\src\test.checks\z0.test.checks.csproj
dotnet sln add d:\dev\projects\z0\src\test.shell\z0.test.shell.csproj
dotnet sln add d:\dev\projects\z0\src\test.units\z0.test.units.csproj
dotnet sln add d:\dev\projects\z0\src\tools\z0.tools.csproj
dotnet sln add d:\dev\projects\z0\src\validity\z0.validity.csproj
