export * from "./cmd"
export * as Cmd from "./cmd"
export * from "./digital"
export * from "./expr"
export * from "./fs"
export * as FS from "./fs"
export * from "./nats"
export * from "./symbols"
export * from "./uri"
export * from "./common"
export * from "./tools"
export * as Tk from "./tokens"
export * as Wf from "./wf"
export * from "./literals"
export * from "./vars"
export * from "./context"
export * from "./lookup"
export * from "./kinds"
export * from "./values"
export * from "./kinds"
export * from "./locations"
//export * from "./services"
export * as Grammar from "./grammar"
export * as Links from "./links"
export * from "./archives"
export * from "./external"
export * from "./sets"
export * as Text from "./text"
export * as Env from "./env"

export type Strings = Array<string>


export type Script = string

